sudo: required
services:
  - docker

before_install:
  - docker build -t tonyzaa11/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true tonyzaa11/react-test npm test

after_success:
  - docker build -t tonyzaa11/multi-client ./client
  - docker build -t tonyzaa11/multi-nginx ./nginx
  - docker build -t tonyzaa11/multi-server ./server
  - docker build -t tonyzaa11/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tonyzaa11/multi-client
  - docker push tonyzaa11/multi-nginx
  - docker push tonyzaa11/multi-server
  - docker push tonyzaa11/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multti-docker
  env: MulttiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-780608562012
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY