
sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tonyzaa11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tonyzaa11/react-test npm test

after_success:
  - docker build -t tonyzaa11/multi-client ./client
  - docker build -t tonyzaa11/multi-nginx ./nginx
  - docker build -t tonyzaa11/multi-server ./server
  - docker build -t tonyzaa11/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push tonyzaa11/multi-client
  - docker push tonyzaa11/multi-nginx
  - docker push tonyzaa11/multi-server
  - docker push tonyzaa11/multi-worker